
# Webアプリケーション設定
spring:
  # H2コンソールを有効化(本番環境では無効にすればよい)
  # ちなみに、開発者ツールを取り込んでいる場合は設定不要(デフォルトでtrue??)
  h2:
    console:
      enabled: true
      
  # DB設定
  datasource:
    # コネクションライブラリにHikariCP（ヒカリシーピー）を使う
    type: com.zaxxer.hikari.HikariDataSource
    # 利用するドライバ、H2を使う場合はこの値で固定
    driver-class-name: org.h2.Driver
    # インメモリで使い、データベース名はtestdbとする
    # url: jdbc:h2:mem:testdb
    url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    hikari:
      pool-name: ConnectionPool
      leak-detection-threshold: 5000
      maximum-pool-size: 10
      minimum-idle: 5
      username: sa
      password: 
      driver-class-name: org.h2.Driver

  # sql読み込み先
  sql:
    init:
      schema-locations:
        - classpath:initsql/schema.sql
        - classpath:org/springframework/security/core/userdetails/jdbc/users.ddl
      data-locations:
        - classpath:initsql/data.sql
      # (DB初期化用SQL↑実行を)常に行う.EMBEDDED=h2dbのとき、の意味. ALWAYSは無条件
      mode: embedded

  #jpa
  jpa:
    #data.sqlをschema.sqlの後に読み込むように設定
    defer-datasource-initialization: true

