-- DROP TABLE IF EXISTS BOOK;

CREATE TABLE IF NOT EXISTS BOOK (
	-- mysql用のsqlに変更
    -- ID IDENTITY NOT NULL PRIMARY KEY,
    ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS USER_COMMENT (
	ID NUMBER(10) AUTO_INCREMENT, -- 主キーとしてふさわしいものがないのでIDを採番
	NAME VARCHAR2(20),
	MAILADDRESS VARCHAR2(100),
	TEXT VARCHAR2(400) NOT NULL,
	CONSTRAINT ID_PKC PRIMARY KEY(ID) -- IDをプライマリキーとする。(プライマリキーの名前をID_PKCとする)
);
